---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: service
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
