apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: keel
spec:
  type: ClusterIP
  selector:
    app: keel
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: http
