apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gatewayclasses/status
      - gateways
      - gateways/status
      - httproutes
      - httproutes/status
      - grpcroutes
      - grpcroutes/status
      - tlsroutes
      - tlsroutes/status
      - tcproutes
      - tcproutes/status
      - udproutes
      - udproutes/status
      - referencegrants
      - referencegrants/status
      - backendtlspolicies
      - backendtlspolicies/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch

