apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      insecure: true
      dashboard: true
    serviceAccount:
      create: false
      name: traefik
    providers:
      kubernetesGateway:
        enabled: true
