apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radarr

resources:
  - deployment.yml
  - pvc.yml
  - service.yml
  - namespace.yml
  - ../base

configMapGenerator:
  - name: app-config
    literals:
      - APP_SUBDOMAIN=radarr
      - APP_PORT=7878
      - LAN_HOST=app-name.lan-domain
      - WAN_HOST=app-name.wan-domain

replacements:
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.DOWNLOADS_PATH
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - spec.template.spec.volumes.[name=downloads].hostPath.path
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.APP_SUBDOMAIN
    targets:
      - select:
          kind: ConfigMap
          name: app-config
        fieldPaths:
          - data.LAN_HOST
          - data.WAN_HOST
        options:
          delimiter: "."
          index: 0
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.LAN_DOMAIN
    targets:
      - select:
          kind: ConfigMap
          name: app-config
        fieldPaths:
          - data.LAN_HOST
        options:
          delimiter: "."
          index: 1
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.WAN_DOMAIN
    targets:
      - select:
          kind: ConfigMap
          name: app-config
        fieldPaths:
          - data.WAN_HOST
        options:
          delimiter: "."
          index: 1
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.LAN_HOST
    targets:
      - select:
          kind: IngressRoute
          name: ingress-route
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.WAN_HOST
    targets:
      - select:
          kind: IngressRoute
          name: ingress-route
        fieldPaths:
          - spec.routes.1.match
        options:
          delimiter: "`"
          index: 1
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.APP_PORT
    targets:
      - select:
          kind: IngressRoute
          name: ingress-route
        fieldPaths:
          - spec.routes.0.services.0.port
          - spec.routes.1.services.0.port

labels:
  - includeSelectors: true
    pairs:
      app: radarr
      app.kubernetes.io/managed-by: kustomize
