apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- pvc.yml
- service.yml
- ingress.yml
- namespace.yml

namePrefix: radarr-

namespace: radarr

labels:
- includeSelectors: true
  pairs:
    app: radarr
    app.kubernetes.io/managed-by: kustomize
