apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: jellyfin
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: jellyfin
  name: jellyfin-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

