apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: das
  resources:
    requests:
      storage: 200Gi
  volumeName: archive

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: das
  resources:
    requests:
      storage: 900Gi
  volumeName: vault

