apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    service: jellyfin
spec:
  type: ClusterIP
  selector:
    service: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
