---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lidarr
  name: app
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5h"
    keel.sh/approvals: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Asia/Chongqing
          ports:
            - containerPort: 8686
              protocol: TCP
          resources:
            requests:
              cpu: "400m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /music
              name: music
            - mountPath: /downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: downloads
          hostPath:
            path: /replace/downloads
            type: Directory
        - name: music
          hostPath:
            path: /mnt/vault/music
            type: Directory
