apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault
spec:
  capacity:
    storage: 931Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: das
  hostPath:
    path: /mnt/vault
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive
spec:
  capacity:
    storage: 298Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: das
  hostPath:
    path: /mnt/archive
    type: Directory
